name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Check linting
        run: npm run lint

      - name: Check Environment Variables
       run: |
          echo "POSTGRES_PRISMA_URL: $POSTGRES_PRISMA_URL"
          echo "POSTGRES_URL_NON_POOLING: $POSTGRES_URL_NON_POOLING"

      - name: Build Application
        env:
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
        run: npm run build

      - name: Start Application
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Run Cypress Tests
        run: npm run test

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Video Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
