name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Check linting
        run: npm run lint

      - name: Build Application
        run: npm run build

      - name: Start Application
        run: npm run start &
        env:
          NODE_ENV: test

      # - name: Wait for Application to Start
      #   uses: alexetcheverry/wait-for-it@v1
      #   with:
      #     url: "http://localhost:3000"
      #     timeout: 60

      - name: Run Cypress Tests
        run: npm run test

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Video Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
